services:
  - type: web
    name: derikchat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      PORT: "10000"
      FLASK_SECRET_KEY: "DerikChat"
