services:
  - type: web
    name: derikchat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      PORT: "10000"
      FLASK_SECRET_KEY: "DerikChat"
